# Generated by Django 5.2.9 on 2025-12-22 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'attendance_overrides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField(db_index=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_override', 'Manual Override')], default='pending', max_length=20)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('image_quality_score', models.FloatField(blank=True, null=True)),
                ('vehicle_detected', models.BooleanField(blank=True, null=True)),
                ('people_count', models.PositiveIntegerField(blank=True, null=True)),
                ('validation_details', models.JSONField(blank=True, default=dict)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('applies_to_all', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'validation_rules',
                'ordering': ['name'],
            },
        ),
    ]
