# Generated by Django 5.2.9 on 2026-01-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='validationrule',
            name='departments',
        ),
        migrations.DeleteModel(
            name='AttendanceOverride',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
