# Generated by Django 5.2.9 on 2025-12-22 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('operation', models.CharField(choices=[('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('priority', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_queue',
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
