# Generated by Django 5.2.9 on 2025-12-22 07:42

import apps.faces.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('capturing', 'Capturing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('images_captured', models.PositiveIntegerField(default=0)),
                ('images_accepted', models.PositiveIntegerField(default=0)),
                ('images_rejected', models.PositiveIntegerField(default=0)),
                ('rejection_reasons', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'enrollment_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_vector', models.BinaryField()),
                ('embedding_size', models.PositiveIntegerField(default=512)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'face_embeddings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.faces.models.face_image_upload_path)),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('enrollment', 'Enrollment'), ('attendance', 'Attendance'), ('training', 'Training')], default='enrollment', max_length=20)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField()),
                ('face_detected', models.BooleanField(default=False)),
                ('face_count', models.PositiveIntegerField(default=0)),
                ('face_bbox', models.JSONField(blank=True, null=True)),
                ('face_landmarks', models.JSONField(blank=True, null=True)),
                ('blur_score', models.FloatField(blank=True, null=True)),
                ('lighting_score', models.FloatField(blank=True, null=True)),
                ('occlusion_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'face_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
