# Generated by Django 5.2.9 on 2025-12-22 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faces', '0001_initial'),
        ('ml_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='model_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embeddings', to='ml_models.modelversion'),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='face_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='faces.faceimage'),
        ),
        migrations.AddIndex(
            model_name='faceimage',
            index=models.Index(fields=['user', 'purpose'], name='face_images_user_id_714d30_idx'),
        ),
        migrations.AddIndex(
            model_name='faceimage',
            index=models.Index(fields=['is_valid'], name='face_images_is_vali_d7f47a_idx'),
        ),
        migrations.AddIndex(
            model_name='faceimage',
            index=models.Index(fields=['quality_score'], name='face_images_quality_f3d54c_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['user', 'is_primary'], name='face_embedd_user_id_f78876_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['model_version'], name='face_embedd_model_v_b9afb5_idx'),
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['is_active'], name='face_embedd_is_acti_642bfb_idx'),
        ),
    ]
