# Generated by Django 5.2.9 on 2026-01-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendancerecord_approved_by_and_more'),
        ('faces', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceembedding',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='faceembedding',
            name='model_version',
        ),
        migrations.RemoveField(
            model_name='faceembedding',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faceimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='EnrollmentSession',
        ),
        migrations.DeleteModel(
            name='FaceEmbedding',
        ),
        migrations.DeleteModel(
            name='FaceImage',
        ),
    ]
