# Generated by Django 5.2.9 on 2025-12-22 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_tag', models.CharField(max_length=50, unique=True)),
                ('model_type', models.CharField(choices=[('lightweight', 'Lightweight (On-Device)'), ('heavy', 'Heavy (Server-Side)')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision_score', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_versions',
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='model_versi_model_t_4d2d2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('trigger_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('epochs', models.PositiveIntegerField(blank=True, null=True)),
                ('final_loss', models.FloatField(blank=True, null=True)),
                ('final_accuracy', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='ml_models.modelversion')),
            ],
            options={
                'db_table': 'training_jobs',
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('epoch', models.PositiveIntegerField()),
                ('loss', models.FloatField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('val_loss', models.FloatField(null=True)),
                ('val_accuracy', models.FloatField(null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ml_models.trainingjob')),
            ],
            options={
                'db_table': 'training_logs',
            },
        ),
    ]
