# Generated by Django 5.2.9 on 2025-12-22 10:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name', unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('plan', models.CharField(choices=[('free', 'Free - 5 employees'), ('pro', 'Pro - 50 employees'), ('business', 'Business - Unlimited')], default='free', max_length=20)),
                ('max_employees', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('check_in_start', models.TimeField(default='08:00')),
                ('check_in_end', models.TimeField(default='10:00')),
                ('work_hours', models.IntegerField(default=8, help_text='Expected work hours per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaaSEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(help_text='Company employee ID', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('face_enrolled', models.BooleanField(default=False)),
                ('face_embeddings', models.JSONField(blank=True, default=list, help_text='512-dim ArcFace embeddings')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='employee_faces/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_employees', to='core.organization')),
            ],
            options={
                'db_table': 'saas_employees',
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('organization', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='SaaSAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('leave', 'On Leave'), ('holiday', 'Holiday')], default='absent', max_length=20)),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('check_in_confidence', models.FloatField(blank=True, null=True)),
                ('check_out_confidence', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_attendance', to='core.organization')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.saasemployee')),
            ],
            options={
                'db_table': 'saas_attendance',
                'ordering': ['-date', 'employee__first_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
