# Generated by Django 5.2.9 on 2025-12-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_saas_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_code',
            field=models.CharField(default='DEFAULT', help_text='Simple code like ACME or OFFICE1', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='password',
            field=models.CharField(default='1234', help_text='Simple password for kiosk access', max_length=50),
            preserve_default=False,
        ),
    ]
