# Generated by Django 5.2.9 on 2025-12-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_org_code_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasemployee',
            name='image_count',
            field=models.IntegerField(default=0, help_text='Number of captured face images'),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='last_trained_at',
            field=models.DateTimeField(blank=True, help_text='When model was last trained', null=True),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='training_mode',
            field=models.CharField(blank=True, help_text='light or heavy', max_length=20),
        ),
    ]
