# Generated by Django 5.2.9 on 2025-12-23 05:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_training_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saasattendance',
            old_name='check_in_time',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='saasattendance',
            old_name='check_out_time',
            new_name='check_out',
        ),
        migrations.AlterUniqueTogether(
            name='saasattendance',
            unique_together={('organization', 'employee', 'date')},
        ),
        migrations.AddField(
            model_name='saasattendance',
            name='work_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='captured_embeddings',
            field=models.JSONField(blank=True, default=list, help_text='Embeddings waiting for training'),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='image_status',
            field=models.CharField(choices=[('pending', 'Pending Capture'), ('captured', 'Images Captured'), ('approved', 'Approved'), ('trained', 'Model Trained')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='saasattendance',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='saasattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.saasemployee'),
        ),
        migrations.AlterField(
            model_name='saasattendance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='saasattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('leave', 'On Leave'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='saasemployee',
            name='last_trained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='saasattendance',
            name='work_hours',
        ),
    ]
