# Generated by Django 5.2.9 on 2025-12-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_capture_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saasemployee',
            options={},
        ),
        migrations.AddField(
            model_name='organization',
            name='recognition_mode',
            field=models.CharField(choices=[('light', 'Light (Quick)'), ('heavy', 'Heavy (DeepFace)')], default='light', help_text='Which model to use for kiosk face recognition', max_length=20),
        ),
    ]
