# Generated by Django 5.2.9 on 2025-12-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_recognition_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasemployee',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Last login time', null=True),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='password',
            field=models.CharField(blank=True, help_text="Employee's login password", max_length=50),
        ),
    ]
