# Generated by Django 5.2.9 on 2025-12-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasemployee',
            name='heavy_accuracy',
            field=models.FloatField(blank=True, help_text='Last test accuracy %', null=True),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='heavy_embeddings',
            field=models.JSONField(blank=True, default=list, help_text='Heavy model embeddings (512-dim)'),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='heavy_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='heavy_trained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='light_accuracy',
            field=models.FloatField(blank=True, help_text='Last test accuracy %', null=True),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='light_embeddings',
            field=models.JSONField(blank=True, default=list, help_text='Light model embeddings (128-dim)'),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='light_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saasemployee',
            name='light_trained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saasemployee',
            name='face_embeddings',
            field=models.JSONField(blank=True, default=list, help_text='Active embeddings for recognition'),
        ),
        migrations.AlterField(
            model_name='saasemployee',
            name='training_mode',
            field=models.CharField(blank=True, help_text='Currently active model: light or heavy', max_length=20),
        ),
    ]
