# Generated by Django 5.2.9 on 2025-12-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_dual_model_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasemployee',
            name='captured_embeddings_light',
            field=models.JSONField(blank=True, default=list, help_text='face-api.js 128-d embeddings for light model'),
        ),
        migrations.AlterField(
            model_name='saasemployee',
            name='captured_embeddings',
            field=models.JSONField(blank=True, default=list, help_text='DeepFace 512-d embeddings for heavy model'),
        ),
    ]
