# Generated by Django 5.2.9 on 2025-12-29 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_captured_embeddings_light'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomYoloModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Admin-defined name for this model', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_file', models.FileField(help_text='.pt YOLO model file', upload_to='yolo_models/')),
                ('classes', models.JSONField(default=list, help_text='Classes this model can detect')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yolo_models', to='core.organization')),
            ],
            options={
                'db_table': 'custom_yolo_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginDetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('face_confidence', models.FloatField(help_text='Face recognition confidence 0-1')),
                ('detections', models.JSONField(default=dict, help_text='{"helmet": true, "vest": false}')),
                ('compliance_passed', models.BooleanField(default=True)),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='login_frames/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to='core.saasemployee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to='core.organization')),
                ('yolo_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_results', to='core.customyolomodel')),
            ],
            options={
                'db_table': 'login_detection_results',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DetectionRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(help_text='Name of the class to detect', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Human-readable name', max_length=200)),
                ('is_required', models.BooleanField(default=False, help_text='If true, login fails without this object')),
                ('yolo_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.customyolomodel')),
            ],
            options={
                'db_table': 'detection_requirements',
                'unique_together': {('yolo_model', 'class_name')},
            },
        ),
    ]
