# Generated by Django 5.2.9 on 2025-12-29 08:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_yolo_detection_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='attendance_mode',
            field=models.CharField(choices=[('daily', 'Daily (First In/Last Out)'), ('continuous', 'Continuous (Log Every Scan)')], default='daily', help_text='How attendance is calculated and stored', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='compliance_enforcement',
            field=models.CharField(choices=[('block', 'Block Entry on Failure'), ('report', 'Allow & Report Failure')], default='report', help_text='Action to take when object detection rules (helmet/vest) fail', max_length=20),
        ),
        migrations.AlterField(
            model_name='customyolomodel',
            name='model_file',
            field=models.FileField(help_text='.pt YOLO model file', upload_to=core.models.yolo_model_upload_path),
        ),
    ]
