# Generated by Django 5.2.9 on 2025-12-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_organization_attendance_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasattendance',
            name='verification_method',
            field=models.CharField(blank=True, help_text='face_employee_dashboard, face_realtime, etc.', max_length=50),
        ),
    ]
