# Generated by Django 5.2.9 on 2025-12-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_saasattendance_verification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetectionresult',
            name='login_source',
            field=models.CharField(default='multi_login', help_text='multi_login or employee_dashboard', max_length=50),
        ),
    ]
