# Generated by Django 5.2.9 on 2025-12-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_logindetectionresult_login_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasemployee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('driver', 'Driver')], default='driver', help_text="Employee's role in the organization", max_length=20),
        ),
    ]
