# Generated by Django 5.2.9 on 2025-12-31 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_saasemployee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleComplianceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_image', models.ImageField(help_text='Original captured vehicle image', upload_to='vehicle_compliance/')),
                ('annotated_image', models.ImageField(blank=True, help_text='Image with detection boxes drawn', null=True, upload_to='vehicle_compliance/annotated/')),
                ('detections', models.JSONField(default=dict, help_text='{"hooter": true, "logo": false, "number_plate": true, ...}')),
                ('compliance_passed', models.BooleanField(default=True, help_text='Did vehicle pass compliance check?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_compliance_records', to='core.saasemployee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_compliance_records', to='core.organization')),
                ('yolo_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_compliance_records', to='core.customyolomodel')),
            ],
            options={
                'db_table': 'vehicle_compliance_records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
