# Generated by Django 5.2.9 on 2026-01-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vehiclecompliancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetectionresult',
            name='login_source',
        ),
        migrations.RemoveField(
            model_name='saasemployee',
            name='role',
        ),
        migrations.AlterField(
            model_name='saasattendance',
            name='verification_method',
            field=models.CharField(blank=True, default='', help_text='face_employee_dashboard, face_realtime, etc.', max_length=50),
        ),
        migrations.DeleteModel(
            name='VehicleComplianceRecord',
        ),
    ]
