# Generated by Django 5.2.9 on 2026-01-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_logindetectionresult_login_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasemployee',
            name='role',
            field=models.CharField(blank=True, default='driver', help_text='Employee role', max_length=50),
        ),
    ]
