# Generated by Django 5.2.9 on 2026-01-04 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_saasemployee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleComplianceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle_image', models.ImageField(upload_to='vehicle_compliance/')),
                ('detections', models.JSONField(default=dict, help_text='{"hooter": true, "number_plate": true}')),
                ('compliance_passed', models.BooleanField(default=False)),
                ('compliance_details', models.JSONField(default=dict, help_text='Full compliance check result')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_compliance_records', to='core.organization')),
                ('yolo_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customyolomodel')),
            ],
            options={
                'db_table': 'vehicle_compliance_records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('helper_skipped', models.BooleanField(default=False)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_compliance_passed', models.BooleanField(default=False)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_compliance_passed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('driver_checked_in', 'Driver Checked In'), ('helper_checked_in', 'Helper Checked In'), ('helper_skipped', 'Helper Skipped'), ('checkin_complete', 'Check-in Complete'), ('checkout_started', 'Checkout Started'), ('completed', 'Trip Completed'), ('incomplete', 'Incomplete')], default='driver_checked_in', max_length=30)),
                ('work_duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_driver_detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_checkin_driver', to='core.logindetectionresult')),
                ('checkin_helper_detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_checkin_helper', to='core.logindetectionresult')),
                ('checkout_driver_detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_checkout_driver', to='core.logindetectionresult')),
                ('checkout_helper_detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_checkout_helper', to='core.logindetectionresult')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to='core.saasemployee')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_helper', to='core.saasemployee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.organization')),
                ('checkin_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_checkin', to='core.vehiclecompliancerecord')),
                ('checkout_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_checkout', to='core.vehiclecompliancerecord')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-date', '-checkin_time'],
            },
        ),
    ]
