# Generated by Django 5.2.9 on 2026-01-09 05:22

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_trip_checkin_latitude_trip_checkin_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Route code (e.g., R1, R2, A01)', max_length=20)),
                ('name', models.CharField(help_text='Route name or description', max_length=100)),
                ('name_hindi', models.CharField(blank=True, help_text='Route name in Hindi', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Route details, landmarks, etc.')),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated time to complete route (hours)', max_digits=4, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Route distance in kilometers', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['ward', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='logindetectionresult',
            name='frame_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.login_frame_upload_path),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Area/Zone name (e.g., North Zone)', max_length=100)),
                ('name_hindi', models.CharField(blank=True, help_text='Area name in Hindi', max_length=100)),
                ('code', models.CharField(help_text='Short code (e.g., NZ, SZ)', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.organization')),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Assigned garbage collection route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.route'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(help_text='Ward number (e.g., 1, 2, 3)')),
                ('name', models.CharField(blank=True, help_text='Optional ward name', max_length=100)),
                ('name_hindi', models.CharField(blank=True, help_text='Ward name in Hindi', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('population', models.IntegerField(blank=True, help_text='Estimated population', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.area')),
            ],
            options={
                'db_table': 'wards',
                'ordering': ['area', 'number'],
                'unique_together': {('area', 'number')},
            },
        ),
        migrations.AddField(
            model_name='route',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('ward', 'code')},
        ),
    ]
