# Generated by Django manually on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_trip_checkin_latitude_trip_checkin_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecompliancerecord',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Extracted number plate text from OCR', max_length=50, null=True),
        ),
    ]
