# Generated by Django 5.2.9 on 2026-01-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_route_alter_logindetectionresult_frame_image_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='number',
            field=models.CharField(help_text='Ward number/code (e.g., 1, 2, commercial02)', max_length=50),
        ),
    ]
