# Generated by Django 5.2.9 on 2026-02-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vehiclecompliancerecord_plate_number'),
        ('core', '0020_ward_number_to_charfield'),
    ]

    operations = [
    ]
