# Generated by Django 5.2.9 on 2026-02-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20260211_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_substitute_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_substitute_helper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='substitute_driver_license',
            field=models.ImageField(blank=True, null=True, upload_to='substitutes/licenses/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='substitute_driver_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='substitute_driver_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='trip',
            name='substitute_driver_photo',
            field=models.ImageField(blank=True, null=True, upload_to='substitutes/drivers/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='substitute_helper_photo',
            field=models.ImageField(blank=True, null=True, upload_to='substitutes/helpers/'),
        ),
    ]
