# Generated by Django 5.2.9 on 2026-02-24 03:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_trip_is_substitute_driver_trip_is_substitute_helper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(help_text='Official license plate number (e.g. RJ14XX1234)', max_length=50)),
                ('name', models.CharField(blank=True, help_text='Optional name or description (e.g. Truck 1)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, help_text='Area where this vehicle operates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.area')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.organization')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['plate_number'],
                'unique_together': {('organization', 'plate_number')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Assigned vehicle for this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.vehicle'),
        ),
    ]
